name: Transcribe YouTube Video

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Decrypt cookies
        env:
          COOKIES: ${{secrets.COOKIES}}
        run: >
          gpg 
          --quiet
          --batch
          --yes
          --decrypt
          --passphrase="$COOKIES"
          --output ./cookies.txt
          cookies.txt.gpg

      - name: Install Vosk
        run: |
          pip3 install vosk

      - name: Install FFMPEG
        run: |
          sudo apt install ffmpeg
          ffmpeg --help

      - name: Install YT-DLP
        run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/download/2025.07.21/yt-dlp
          chmod +x yt-dlp

      - name: Download audio
        env:
          URL: ${{secrets.YOUTUBE_PLAYLIST}}
        run: |
          ./yt-dlp --playlist-items -1 --audio-quality 6 --audio-format mp3 -x --cookies cookies.txt --output audio $URL

      - name: Transcribe
        run: |
          vosk-transcriber -i audio.mp3 -o transcription.srt

      - uses: actions/upload-artifact@v4
        with:
          name: Axelor8.${{github.run_number}}
          path: transcription.srt
