name: Transcribe YouTube Video

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: >
          gpg 
          --quiet
          --batch
          --yes
          --decrypt
          --passphrase="$COOKIES"
          --output ./cookies.txt
          cookies.txt.gpg
        name: Decrypt cookies

      - run: |
          sudo apt install  ffmpeg
          ffmpeg --help
        name: Install FFMPEG

      - run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/download/2025.07.21/yt-dlp
          chmod +x yt-dlp
          ./yt-dlp --audio-quality 6 --audio-format mp3 -x $URL --cookies cookies.txt
        name: Install YT-DLP
        env:
          URL: ${{secrets.YOUTUBE_PLAYLIST}}
