name: Transcribe YouTube Video

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install  ffmpeg
          ffmpeg --version
      - run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/download/2025.07.21/yt-dlp
          chmod +x yt-dlp
          ./yt-dlp -x
        env:
          URL: ${{secrets.YOUTUBE_PLAYLIST}}
