name: Transcribe YouTube Video

on:
  workflow_dispatch:

jobs:
  transcribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: >
          gpg 
          --quiet
          --batch
          --yes
          --decrypt
          --passphrase="$COOKIES"
          --output ./cookies.txt
          cookies.txt.gpg
        name: Decrypt cookies
        env:
          COOKIES: ${{secrets.COOKIES}}

      - name: Install Vox
        run: |
          pip3 install vosk

      - name: Install FFMPEG
        run: |
          sudo apt install  ffmpeg
          ffmpeg --help

      - name: Install YT-DLP
        run: |
          wget https://github.com/yt-dlp/yt-dlp/releases/download/2025.07.21/yt-dlp
          chmod +x yt-dlp

      - name: Download and transcribe
        env:
          URL: ${{secrets.YOUTUBE_PLAYLIST}}
        run: |
          ./yt-dlp --playlist-items -1 --audio-quality 6 --audio-format mp3 -x $URL --cookies cookies.txt
